apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spine-data
  labels:
    app: spine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
