apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtg-deck-shuffler-data
  labels:
    app: mtg-deck-shuffler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3