apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtg-deck-shuffler-data
  namespace: mtg-deck-shuffler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2  # AWS EBS default